/******************************************************************************/
/***               Generated by IBExpert 23.02.2026 13:05:00                ***/
/******************************************************************************/

SET SQL DIALECT 3;

CREATE TABLE "modelgoods_external_images" (
    "id"          ID_TYPE /* ID_TYPE = CHAR(12) DEFAULT '0' NOT NULL */,
    "modelid"     ID_TYPE /* ID_TYPE = CHAR(12) DEFAULT '0' NOT NULL */,
    "url"         VARCHAR(2000) COLLATE PXW_CYRL,
    "is_approved" "d_integer" /* "d_integer" = INTEGER DEFAULT 0 NOT NULL */,
    "is_loaded_to_db" "d_integer" /* "d_integer" = INTEGER DEFAULT 0 NOT NULL */,
    "created_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "userid"      ID_TYPE /* ID_TYPE = CHAR(12) DEFAULT '0' NOT NULL */
);

ALTER TABLE "modelgoods_external_images" ADD CONSTRAINT "PK_modelgoods_external_images" PRIMARY KEY ("id");

CREATE INDEX "idx_modelgoods_external_images_modelid" ON "modelgoods_external_images" ("modelid");

ALTER TABLE "modelgoods_external_images" ADD CONSTRAINT "FK_modelgoods_external_images_modelid" 
    FOREIGN KEY ("modelid") REFERENCES "modelgoods"("id");

SET TERM ^ ;

CREATE OR ALTER TRIGGER "modelgoods_external_images_BI0" FOR "modelgoods_external_images"
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new."id"=UID_NULL()) then begin
    select "oID"
    from "GetID"('modelgoods_external_images')
    into new."id";
  end
  
  if (new."url" is null) then new."url"='';
  if (new."is_approved" is null) then new."is_approved"=0;
  if (new."is_loaded_to_db" is null) then new."is_loaded_to_db"=0;
  if (new."userid" is null) then new."userid"='0';
end
^

CREATE OR ALTER TRIGGER "modelgoods_external_images_BU0" FOR "modelgoods_external_images"
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
  if (new."url" is null) then new."url"='';
  if (new."is_approved" is null) then new."is_approved"=0;
  if (new."is_loaded_to_db" is null) then new."is_loaded_to_db"=0;
  if (new."userid" is null) then new."userid"='0';
  
  new."updated_at" = CURRENT_TIMESTAMP;
end
^

SET TERM ; ^